dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.15.0/bazel_0.15.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.15.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.15.0-linux-x86_64.deb

script:
  - bazel build //projects/grpc-web/backend/...

