dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.7.1/bazel_3.7.1-linux-x86_64.deb
  - sha256sum -c bazel_3.7.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_3.7.1-linux-x86_64.deb

script:
  - bazel build :all

