// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package LMS

type AnyPayload = byte
const (
	AnyPayloadNONE AnyPayload = 0
	AnyPayloadStringValue AnyPayload = 1
	AnyPayloadNumberValue AnyPayload = 2
	AnyPayloadPhone AnyPayload = 3
)

var EnumNamesAnyPayload = map[AnyPayload]string{
	AnyPayloadNONE:"NONE",
	AnyPayloadStringValue:"StringValue",
	AnyPayloadNumberValue:"NumberValue",
	AnyPayloadPhone:"Phone",
}

