// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package LMS

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NumberValue struct {
	_tab flatbuffers.Table
}

func GetRootAsNumberValue(buf []byte, offset flatbuffers.UOffsetT) *NumberValue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NumberValue{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NumberValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NumberValue) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NumberValue) Value() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *NumberValue) MutateValue(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func NumberValueStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NumberValueAddValue(builder *flatbuffers.Builder, value float64) {
	builder.PrependFloat64Slot(0, value, 0.0)
}
func NumberValueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
